server:
  port: 8091
  tomcat:
    max-threads: 10
spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  #添加nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 9999 #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: 192.168.125.110:8080 #指定控制台服务的地址
        clientIp: 192.168.125.110


ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule



##开启Ribbon的饥饿加载模式
#ribbon.eager-load.enabled=true
##指定需要饥饿加载的服务名
#ribbon.eager-load.clients=nacos-provider-service
##Ribbon的超时
#ribbon.ConnectTimeout=3000
#ribbon.ReadTimeout=60000
##对第一次请求的服务的重试次数
#ribbon.MaxAutoRetries=1
##要重试的下一个服务的最大数量（不包括第一个服务）
#ribbon.MaxAutoRetriesNextServer=1
##无论是请求超时或者socket read timeout都进行重试
#ribbon.OkToRetryOnAllOperations=true
##默认随机策略
#ribbon.NFLoadBalancerRuleClassName=com.netflix.loadbalancer.RandomRule
